### ISSUE TITLE
Allow tagging of anyone in your project team

### ISSUE THREAD

**Issue by grahammcculloch** [appdevdesigns/adroit-mobile#10]
* Probably needs a new (mobile-specific) API endpoint (instead of using `/fcf_activities/mobile/myteams`)
* Updated logic required for the AddPhoto page etc.

**Comment by grahammcculloch** [comment]
Implemented. Just waiting on a couple backend issues to be resolved:

1. 'Nucharat Tangtakul' is listed as one of the project members for DigiServe (DGS) on my Adroit mobile app. Is that Pong? Why is he not listed on the web app as someone I can tag?
1. I still only see one project ([DGS]) for graham.mcculloch on Adroit mobile. But on the web app I also see the [TEST] project (and the Test Ministry and Test Admin teams). We should probably get the behaviour the same before I publish any update.

cc @jamesduncan

**Comment by jamesduncan** [comment]
Okay...issues are all Access database related. There needs to be person -> project records created for the Test project before it will show in the new API. The old just grabbed all ministry teams even if you were not connected to the project itself the new one requires the project to place the team under. I made two entries manually one for me and one for you to connect to the Test project and it seems to work well. I will reach out to Bruce to make this change in Access as well.

**Comment by grahammcculloch** [comment]
Deployed in v1.2.0!
