### ISSUE TITLE
tagged people missing from /fcf_activities/mobile/myactivityimages response

### ISSUE THREAD

**Issue by grahammcculloch** [appdevdesigns/adroit-mobile#24]
Previously we didn't care about fetching tagged people on the activity images listed in the mobile app. But now we do as we might need to edit one of those activity images.

Can we add `tagged_people` to the activityImage objects returned by the `/fcf_activities/mobile/myactivityimages` in the format:

```
tagged_people: [
  {
    IDPerson
    display_name
    avatar
  }
  ...
]
```

**Comment by jamesduncan** [comment]
Good catch...I can take a look at getting that for ya.

**Comment by jamesduncan** [comment]
Okay I just about have it ready...will you just need their ID since you have the master list of team members already?

**Comment by grahammcculloch** [comment]
In theory we could just get the IDs but I’m anticipating situations where a
tagged person for whatever reason is no longer in the list of project
members. In this situation I think it’s best to keep that person as one of
the tagged people if editing that image, rather than not display them
because their ID wasn’t found in the list of project members.

G.

**Comment by jamesduncan** [comment]
Fair enough...I already set it up the way you asked but did not include the avatar because of the extra processing required to fetch it...I can do that as well if it is needed since you will not be referencing the master list. Will you need it?

**Comment by grahammcculloch** [comment]
Will it significantly increase the roundtrip time for that API call? It’s
not too bad if we don’t include it - I’ll just have to look up the avatar
for each user ID (on a photo I’m editing) in my cache of project people.
And if the user ID is not found I just display the placeholder avatar
image.

G.

**Comment by grahammcculloch** [comment]
`tagged_people` is now part of the activity image object returned. It doesn't contain the `avatar` field but I look this up in the app from the list of project users and attempt to populate it from there.
