### ISSUE TITLE
Add `createdAt` to POST response

### ISSUE THREAD

**Issue by grahammcculloch** [appdevdesigns/adroit-mobile#48]
Applies to:
* `/fcf_activities/activityimage/create`
* `/fcf_activities/activityimage/update/${activityImageId}`

Currently the `createdAt` field is not included in the response to these POST requests. This means that the newly uploaded activity is not reliably inserted into the correct place in the list of the user's activity images in the mobile app.

Adding this field should not cause any backwards-compatibility issues - so it should be ok to release at any point.

**Comment by jamesduncan** [comment]
I have added this into the /create API response but not the /update because the "createdAt" doesn't change when updated but there is an "updatedAt" if we would like to reveal it.

**Comment by jamesduncan** [comment]
I will push the current changes as soon as the server doesn't have much traffic and will let you know when they are live.

**Comment by grahammcculloch** [comment]
>I have added this into the /create API response but not the /update because the "createdAt" doesn't change when updated but there is an "updatedAt" if we would like to reveal it.

FYI personally I don't like this approach to APIs... I think the objects returned from POST and PATCH should be the same. Otherwise its so easy to introduce hard-to-spot bugs where our data objects have fields missing based on whether they've been updated or not etc etc.

**Comment by jamesduncan** [comment]
So the best solution would be to add both createdAt and updatedAt to the /create and /update APIs so you have access to whichever you need at the time?

**Comment by grahammcculloch** [comment]
I think that's probably better, yes - at least it's heading in the right direction.
